---
title: "Deliverable 1"
output: html_document
---

```{r setup}
library(tidyverse)
```

# For the writeup, see CS506 Final Project - Deliverable 1.pdf

## Cleaning Data
```{r clean_data}
data <- read.csv(file = '../data/vaccinationrate_and_exemption.csv')
spending_data_headers <- read.csv(file = '../data/healthExpendituresState.csv', skip = 1, nrows = 1, as.is = TRUE)
spending_data = read.csv(file = '../data/healthExpendituresState.csv', skip = 3, nrows = 51, as.is = TRUE)
colnames(spending_data) = spending_data_headers
spending_data$`Total Health Spending` = gsub("\\$", "", spending_data$`Total Health Spending`)
spending_data$`Total Health Spending` = as.numeric(gsub("\\,", "", spending_data$`Total Health Spending`))
spending_data <- spending_data %>% rename(
                    States = Location
)
population_data <- read.csv(file = '../data/population_by_state.csv')
population_data <- population_data[order(population_data$States),]
population_data$Population = as.numeric(gsub("\\,", "", population_data$Population))
all_data <- merge(data, spending_data, by="States")
all_data <- merge(all_data, population_data, by="States")
all_data <- all_data %>% rename(VaxRate = `X.`)
all_data <- all_data %>% mutate(spending_per_capita = (`Total Health Spending`/Population)*1000000)
```
## Exemptions

```{r make_simple_graph}
ggplot(all_data) +
  #geom_point(aes(x = Exemption, y=X.)) +
  geom_boxplot(aes(x = Exemption, y=VaxRate)) +
  ylab("Vaccination Rate") +
  ggtitle("Vaccination Rates in States with Various Exemptions")

```

## Spending per Capita by State

```{r graphs2}
model <- lm(VaxRate~spending_per_capita, data = all_data)
summary(model)
```
