---
title: "Clean_data"
output: pdf_document
---
Setup
```{r setup, include=FALSE}
library(tidyverse)
```

Import and Clean Health Expenditures Data
```{r clean_healthExpenditures}
# data from 2014
healthcareSpending_headers <- read.csv(file = '../../data/healthExpendituresState.csv', skip = 1, nrows = 1, as.is = TRUE)
healthcareSpending = read.csv(file = '../../data/healthExpendituresState.csv', skip = 3, nrows = 51, as.is = TRUE)
colnames(healthcareSpending) = healthcareSpending_headers
healthcareSpending$`Total Health Spending` = gsub("\\$", "", healthcareSpending$`Total Health Spending`)
healthcareSpending$`Total Health Spending` = as.numeric(gsub("\\,", "", healthcareSpending$`Total Health Spending`))
healthcareSpending <- healthcareSpending %>% rename(States = Location)
```

Import and Clean Population Data
```{r clean_population_by_state}
# data from 2019
population <- read.csv(file = '../../data/population_by_state.csv')
population <- population[order(population$States),]
population$Population = as.numeric(gsub("\\,", "", population$Population))
```

Import and Clean Vaccination Rate Data
```{r vaccination rate}
# data from 2007-2017
vaccinationRate <- read.csv(file = '../../data/vaccination_19_35months_exemption.csv')
vaccinationRate = vaccinationRate %>% 
                  rename(
                    `2007` = X2007,  
                    `2008` = X2008,
                    `2009` = X2009,
                    `2010` = X2010,
                    `2011` = X2011,
                    `2012` = X2012,
                    `2013` = X2013,
                    `2014` = X2014,
                    `2015` = X2015,
                    `2016` = X2016,
                    `2017` = X2017
)
```

Import and CleanPopulation Density Data
```{r populationDensity}
# data from 2020
populationDensity <- read.csv(file = '../../data/populationDensity.csv')
populationDensity <- subset(populationDensity, select=c('States', 'Density'))
populationDensity = populationDensity %>% rename(population_density = Density)
```

Import and Clean Median Income Data
```{r medianIncome}
# data from 2017
medianIncome <- read.csv(file = '../../data/medianHouseholdIncome.csv')
medianIncome <- subset(medianIncome, select=c('States', 'Median_income'))
medianIncome$Median_income = as.numeric(gsub("\\,", "", medianIncome$Median_income))
```

Import Educational Attainment Data
```{r educational_attainment}
# data from 2020
educational_attainment <- read.csv(file = '../../data/educational_attainment.csv')
```

Import and Clean Educational Spending Data
```{r educationSpending}
# data from 2016
educationSpending <- read.csv(file = '../../data/EducationSpending.csv')
educationSpending$`spending_per_pupil` = gsub("\\$", "", educationSpending$`spending_per_pupil`)
educationSpending$`spending_per_pupil` = as.numeric(gsub("\\,", "", educationSpending$`spending_per_pupil`))
```

Merge and Export all Data to .csv
```{r merge_all_data and export}
# Vaccination data is from 2017, Exemption is from 2020, Healthcare spending is from 2014

data <- merge(vaccinationRate, healthcareSpending, by="States")
data <- merge(data, population, by="States")
data <- data %>% mutate(spending_per_capita = (`Total Health Spending`/Population)*1000000)
data <- merge(data, populationDensity, by="States")
data <- merge(data, medianIncome, by="States")
data <- merge(data, educational_attainment, by="States")
data <- merge(data, educationSpending, by="States")
write.csv(data, "data/full_data.csv")
```




